### ISSUE TITLE
[BUG] Pure Worship intro image for chapter not included

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/jw-meeting-media-fetcher#148]
**Describe the bug**
The Pure Worship (rr) images at the top of every chapter are not included when that week we start on a new chapter. The introductory video is included, but I also expect the image to be included.

**To Reproduce**
1. Go to 'Home'
2. Click on 'Get Media!'
3. Open target folder
4. See that chapter image is missing

**Expected behavior**
The image at the top of the chapter should be included when starting a new chapter and when the paragraph referencing the image is discussed that week (maybe that's not doable, in that case always include the chapter image).

**System specs (please complete the following information):**
 - OS: Windows 10
 - App Version 21.12.1

**Additional context**
Related to #140

**Comment by sircharlo** [comment]
Hello again! 😄 Thanks for pointing out these bugs.
I had also noticed this one, and it was consequently fixed with https://github.com/sircharlo/jw-meeting-media-fetcher/commit/db5e17e141042f91379bc8badf118606b7b82c2d. 
Similarly to issue #147 that you pointed out, I'll release this fix sometime soon, ideally before the next chapter of _rr_ begins, that is on the week of December 27th. I consider that the ship has however already sailed for this week..!
Let me know if you have any thoughts.
_- COS_

**Comment by mtdvlpr** [comment]
No problem! Thank you for all the effort you put and continue putting into this. I am a relatively new user, but I like it very much! I am also considering diving into your code one day with the goal to perhaps be able to contribute 😄

**Comment by sircharlo** [comment]
> No problem! Thank you for all the effort you put and continue putting into this. I am a relatively new user, but I like it very much! I am also considering diving into your code one day with the goal to perhaps be able to contribute 😄

It's my great pleasure! It's turned into quite the project, but I very much enjoy it. 😄 
I will however take all the help that's offered... 😉
